name: Gherkin scenarios for api

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run MongoDB
      run: |
        docker compose -f mongo.yml up -d
    - name: Run flask
      run: |
        flask --app app.api run &
    - name: Run Gherkin Scenarios
      run: |
        python -m behave app/features/
